### ISSUE TITLE
intel-qsv linux version?

### ISSUE THREAD

**Issue by minimal101** [mjb2000/media-autobuild_suite#1]
Hello ..thanks for this great project . Probably is not the place but.....How to get this working on linux.We compiled your FFmpeg,also this one from https://github.com/shenhailuanma/qsv-ffmpeg-codec.On u ffmpeg i get init_MFX-3 on second we get segmaentation fault ! Some 1 can give some output how to make it work on linux !

Thanks in advance.

**Comment by mjb2000** [comment]
Are you trying to compile on Linux, for Linux? If so take a look at [this project](https://github.com/shenhailuanma/ffmpeg-qsv) which I believe is designed for Linux.

This autobuild suite is designed to compile on Windows for Windows.

As I understand it the Linux building process required some additional Intel graphics drivers headers, but to be honest with you I've never really looked in to it.

I would start with building just the ffmpeg + qsv project and it this works take a look at the additional configure options that you might need to include (such as --enable-libvpx --enable-libz264) - You can take a look at the shelll script in the autobuild project to see the complete list of additional libraries that are initially built and the subsequent options that are added to the ffmpeg configure command.

Hope this helps
